# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51d5619904ae02575fb33d3a4b3fcfa9b63015bfb5849276b8b992da9e97cbaae27f0fb599000e88c0a902dc760d0289c94357d86d45c8a1d4a82c76f95cacd5

test:
  secret_key_base: 15efe7ec3a1ef34fcef6dba133497d8261626a9cfb9b30ae5feec670b266d1b344159703acba3c8f4682bc3c49df6bfb9ab39644554d8ae1ee9d8e2ac23ca5b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
